# Generated by Django 2.1 on 2018-10-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingobservations',
            name='clean_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missingobservations',
            name='rows_missing',
            field=models.TextField(blank=True, null=True),
        ),
    ]
