# Generated by Django 2.1 on 2018-10-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0002_auto_20181008_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missingobservations',
            old_name='rows_missing',
            new_name='clean_columns',
        ),
        migrations.AddField(
            model_name='missingobservations',
            name='missing_columns',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingobservations',
            name='missing_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
